
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Aug 17 09:06:02 CEST 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym_novo {
  /* terminals */
  public static final int PLUSPLUS = 16;
  public static final int CONST = 3;
  public static final int RIGHTPAREN = 11;
  public static final int NOTEQUAL = 31;
  public static final int CONTINUE = 37;
  public static final int GREATER = 32;
  public static final int SEMI = 8;
  public static final int LESS = 34;
  public static final int MINUS = 23;
  public static final int CONSTANTCHAR = 42;
  public static final int LEFTPAREN = 10;
  public static final int AND = 27;
  public static final int LESSEQUAL = 35;
  public static final int OR = 28;
  public static final int COMMA = 9;
  public static final int EQUALEQUAL = 30;
  public static final int DOTDOT = 18;
  public static final int DIV = 25;
  public static final int PLUS = 22;
  public static final int IF = 38;
  public static final int DOT = 21;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 17;
  public static final int RETURN = 7;
  public static final int EQUAL = 29;
  public static final int CONSTANTBOOL = 43;
  public static final int NEW = 20;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 24;
  public static final int MOD = 26;
  public static final int IDENT = 40;
  public static final int BREAK = 36;
  public static final int VOID = 6;
  public static final int RIGHTSQUAREBRACE = 15;
  public static final int GREATEREQUAL = 33;
  public static final int RIGHTBRACE = 13;
  public static final int CONSTANTNUM = 41;
  public static final int ELSE = 39;
  public static final int READ = 4;
  public static final int LEFTSQUAREBRACE = 14;
  public static final int LEFTBRACE = 12;
  public static final int QUESTION = 19;
  public static final int PRINT = 5;
}

